### ISSUE TITLE
Feature Request, Help Wanted

### ISSUE THREAD

**Issue by dhruvgupta1730** [EPCSHT/crunchbase-scraper#1]
I am using paid version of the actor at apify, I just wanted to know if the actor can be tweaked to allow for scrapping additional type of url. sample url in the case is https://www.crunchbase.com/funding_round/nomad-health-series-unknown--7db72e6c, any help would be greatly appreciated.

**Comment by tugkan** [comment]
Hey @dhruvgupta1730 ! 

Thank you for communicating about the issue. Do you want to retrieve the URL of the page or something different from the data?

**Comment by dhruvgupta1730** [comment]
@tugkan I should have mentioned that I tried running the scrapper with funding_round url's, but it gives me error for Error: "Wrong URL provided to Start URLS!". it works flawlessly for organization or person url's though :)

**Comment by dhruvgupta1730** [comment]
@tugkan Hi, can you help me ? sorry for being pushy, I am on a shorter timeline.

**Comment by tugkan** [comment]
Hey @dhruvgupta1730 !

It is doable to integrate an extension to retrieve an extra field by a small change. However the actor does not have the feature of `funding_round` URL type at the current moment. Unfortunately it'll be implemented in the next month or so.

If you want to, we can integrate the extension for the supported URL types?

Best

**Comment by dhruvgupta1730** [comment]
@tugkan yaa I think it would be great help, if you add in extension for supported URL types , let me see what I can do with that.

thanks a ton in advance

**Comment by tugkan** [comment]
Hey @dhruvgupta1730 !

We integrated new fields called `extendOutputFunction` and `customMapFunction`. `extendOutputFunction` function takes a Cheerio object and let you expand the data depending on your needs. On the other hand `customMapFunction` let you to create a new field or filter out some of the fields depending on your need. My personal suggestion would be trying to build the URLs by checking the output data by `customMapFunction`.

Best.
